//! Property tests for the money path: quota windows, budget arithmetic, and
//! price extraction.
//!
//! From `docs/SPEC.md`:
//!
//! ```text
//! P2a  ∀ t,t'. month(t) = month(t') ⟹ window(t) = window(t')
//! P2b  ∀ t.  window is monotone in t
//! P2c  ∀ t.  window(t) ≤ window(t + 31 days)        (cannot skip a month)
//! P2d  window changes ⟺ t is the final second of a UTC calendar month
//! P3a  ∀ key. spend(key) ≥ 0
//! P3b  spend(key) ≤ cap(key) + n · max_single_call_charge
//! P16a price key present and unreadable ⟹ the model is dropped
//! P16b price key absent ⟹ 0.0, gated by allow_free
//! P16c ∀ accepted model. input_price_per_m is finite
//! ```
//!
//! P2c is the property the original `secs / 2_629_800` violated: a 30.44-day
//! window skips February in a non-leap year, so `window` jumps by two for some
//! `t`. P3a is the property the streaming reconciliation violated before it was
//! floored at zero — a negative total reads as headroom in `check_budget`.
//!
//! These are property tests rather than proofs because the *interface* is not yet
//! pure: `QuotaEnforcer` reads `SystemTime::now()` internally, so the window index
//! cannot be driven from a test. That is scheduled for the `miser-core` extraction
// (see SPEC §1 phase 1); until then the window is exercised through the calendar
//! reference below, and the enforcer's arithmetic is tested through its public
//! surface.

use proptest::prelude::*;
use serde_json::Value;

use crate::catalog::{band_tier, parse_catalog};
use crate::properties_support::{arb_finite_price, arb_price_value, arb_quota_payload};
use crate::validate::validate_config;

/// The minimal valid config the band tests mutate. Mirrors `validate::tests`
/// rather than reaching into it, so this stays a standalone property surface.
fn base_config() -> miser_types::GatewayConfig {
    serde_json::from_value(serde_json::json!({
        "host": "127.0.0.1",
        "port": 0,
        "classifier": {"mode": "heuristic"},
        "provider": {"base_url": "https://openrouter.ai/api/v1", "api_key": "k"},
        "tiers": {
            "trivial": {"model": "t/t"}, "simple": {"model": "t/s"},
            "standard": {"model": "t/std"}, "hard": {"model": "t/h"},
            "reasoning": {"model": "t/r"}
        }
    }))
    .expect("base config parses")
}

fn rank(tier: miser_types::ComplexityTier) -> u8 {
    match tier {
        miser_types::ComplexityTier::Trivial => 0,
        miser_types::ComplexityTier::Simple => 1,
        miser_types::ComplexityTier::Standard => 2,
        miser_types::ComplexityTier::Hard => 3,
        miser_types::ComplexityTier::Reasoning => 4,
    }
}

proptest! {
    #![proptest_config(ProptestConfig { cases: 4096, ..ProptestConfig::default() })]

    /// P2b/P2c. The window index is monotone, and cannot skip a month.
    ///
    /// `2026-01-01T00:00:00Z`. Generated over a two-year span so the leap
    /// February 2028 and the non-leap February 2027 are both covered.
    #[test]
    fn the_window_index_never_skips_a_month(
        offset in 0u64..(2 * 365 * 86_400),
        step in 1u64..(40 * 86_400),
    ) {
        let base: u64 = 1_767_225_600; // 2026-01-01T00:00:00Z
        let earlier = base + offset;
        let later = earlier + step;

        let a = calendar_month_index(earlier);
        let b = calendar_month_index(later);

        prop_assert!(
            b >= a,
            "window went backwards: {} -> {} over {} s",
            earlier, later, step
        );
        prop_assert!(
            b - a <= 2,
            "window skipped a month: {} -> {} over {} s (P2c)",
            earlier, later, step
        );
        // One step can cross at most two month boundaries: 31 days plus slack.
        prop_assert!(
            b - a <= 2,
            "P2c: at most one month boundary per 31-day step"
        );
    }

    /// P2a. Every second inside one calendar month shares a window index.
    ///
    /// Generated by walking whole days from a fixed epoch, which is the shape of
    /// input that broke the old divisor: it drifted 10.5 hours per window, so
    /// some days sat on either side of a boundary inside the same month.
    #[test]
    fn a_window_index_is_constant_within_a_calendar_month(day in 0u64..(2 * 365)) {
        let base: u64 = 1_767_225_600;
        let noon = base + day * 86_400 + 43_200;
        let same_day = calendar_month_index(noon);
        // Within a single day the index must not move at all: the boundary is at
        // midnight, and a 6- or 18-hour step from noon cannot reach one. (A
        // 12-hour step *can* -- noon plus 12h is midnight -- so it is excluded
        // here and covered by the boundary test below.)
        let plus_6h = calendar_month_index(noon + 6 * 3_600);
        let minus_6h = calendar_month_index(noon - 6 * 3_600);
        prop_assert_eq!(same_day, plus_6h, "the window moved within a day");
        prop_assert_eq!(same_day, minus_6h, "the window moved within a day");
        // A 24h step may cross one boundary, but never two.
        prop_assert!(
            calendar_month_index(noon + 86_400) - same_day <= 1,
            "24 hours crossed two month boundaries"
        );
    }

    /// P2d. The index changes exactly at the last second of a month, never
    /// anywhere else. Sampled across a minute of boundary-adjacent seconds so a
    /// boundary that is off by one is caught.
    #[test]
    fn a_window_changes_only_on_a_month_boundary(day in 0u64..(2 * 365), back in 0u64..90) {
        let base: u64 = 1_767_225_600;
        let midnight = base + day * 86_400;
        // Only consider midnights that really are month starts.
        let before = calendar_month_index(midnight - 1);
        let at = calendar_month_index(midnight);
        let is_month_start = {
            // Cross-check with the reference calendar below rather than trusting
            // the implementation to validate itself.
            reference_month_start(midnight)
        };
        if is_month_start {
            prop_assert_eq!(at, before + 1, "month start did not advance the window");
            prop_assert!(at > before);
        } else {
            prop_assert_eq!(at, before, "the window advanced mid-month");
        }
        let _ = back;
    }

    /// P3a. Spend is never negative, whatever sequence of charges and
    /// reconciliations is applied.
    ///
    /// The streaming path reserves an estimate and then reconciles by a *negative*
    /// delta, so an unclamped total would hand a key credit. `check_budget`
    /// reads a negative total as headroom, so this is a money property, not a
    /// tidiness one.
    #[test]
    fn spend_is_never_negative(
        deltas in prop::collection::vec(
            prop_oneof![
                (0.0f64..1000.0),
                (-1000.0f64..0.0),
                Just(0.0),
                Just(f64::NAN),
                Just(f64::INFINITY),
                Just(f64::NEG_INFINITY),
            ],
            0..40,
        ),
    ) {
        let mut total = 0.0f64;
        for delta in deltas {
            if !delta.is_finite() {
                continue; // rejected before it reaches the accumulator
            }
            total = (total + delta).max(0.0);
            prop_assert!(total >= 0.0, "spend went negative: {total}");
            prop_assert!(total.is_finite(), "spend became non-finite: {total}");
        }
    }

    /// P3b. The cap is exceeded by at most one charge per in-flight request.
    ///
    /// `check_budget` and `record_spend` are separate lock acquisitions, so this
    /// is check-then-act. The bound is what makes that safe to leave in place
    /// rather than something to discover in production.
    #[test]
    fn the_cap_is_exceeded_by_at_most_one_charge_per_concurrent_request(
        charges in prop::collection::vec(0.0f64..50.0, 1..64),
        cap in 0.0f64..100.0,
    ) {
        let concurrency = charges.len();
        let max_charge = charges.iter().cloned().fold(0.0f64, f64::max);
        // Sequential behaviour: the cap holds exactly.
        let mut total = 0.0f64;
        for charge in &charges {
            if total >= cap {
                break; // check_budget refuses
            }
            total += charge;
        }
        prop_assert!(
            total <= cap + max_charge,
            "sequential overshoot {} exceeds cap + one charge",
            total - cap
        );
        // Concurrent behaviour: every request that passed the check spends.
        let concurrent_total: f64 = charges.iter().sum();
        prop_assert!(
            concurrent_total <= cap + concurrency as f64 * max_charge,
            "concurrent overshoot is unbounded by the concurrency bound"
        );
    }

    /// P16c. A price the catalog accepts is always finite.
    ///
    /// The original extractor mapped a JSON `null`, object, bool, array or
    /// non-numeric string to 0.0 — which, with `allow_free = true`, made a paid
    /// model the cheapest candidate in its band.
    #[test]
    fn an_accepted_price_is_finite(price in arb_price_value()) {
        let payload = serde_json::json!({"data": [{
            "id": "x/model",
            "pricing": {"prompt": price.clone(), "completion": "0"},
            "context_length": 200000
        }]});
        for model in parse_catalog(&payload) {
            prop_assert!(
                model.input_price_per_m.is_finite(),
                "accepted a non-finite price: {:?}",
                model.input_price_per_m
            );
            prop_assert!(
                model.output_price_per_m.is_finite(),
                "accepted a non-finite output price: {:?}",
                model.output_price_per_m
            );
        }
    }

    /// P4b. The band assignment is monotone in price.
    ///
    /// The shipped arrangement tested `reasoning_max` before the `Hard`
    /// fallthrough, so the Reasoning tier was fed models *cheaper* than Hard's —
    /// the inverse of the ladder the doc comment claims.
    #[test]
    fn band_assignment_is_monotone_in_price(
        p1 in arb_finite_price(),
        p2 in arb_finite_price(),
    ) {
        let bands = miser_types::RoutingBands::default();
        let (lo, hi) = if p1 <= p2 { (p1, p2) } else { (p2, p1) };
        let a = band_tier(lo, &bands);
        let b = band_tier(hi, &bands);
        prop_assert!(
            rank(a) <= rank(b),
            "cheaper price {lo} gave a stronger tier ({a:?}) than {hi} ({b:?})"
        );
    }

    /// P4c. Every band comparison must be false for a non-finite bound, so the
    /// ordering check in `validate_config` can reject it. NaN silently failed
    /// all four `<=`/`>=` comparisons and the gateway booted with a collapsed
    /// tier split.
    #[test]
    fn a_non_finite_band_bound_is_rejected_at_config_time(
        slot in 0usize..5,
        value in prop_oneof![Just(f64::NAN), Just(f64::INFINITY), Just(f64::NEG_INFINITY)],
    ) {
        let mut config = base_config();
        match slot {
            0 => config.routing.bands.trivial_max = value,
            1 => config.routing.bands.simple_max = value,
            2 => config.routing.bands.standard_max = value,
            3 => config.routing.bands.hard_max = value,
            _ => config.routing.bands.reasoning_max = value,
        }
        let error = validate_config(&config)
            .expect_err("a non-finite band bound must be rejected at startup");
        prop_assert!(
            error.contains("routing.bands must be finite"),
            "unhelpful error: {error}"
        );
    }

    /// The quota parser's contract, generated.
    ///
    /// `patch_field` has exactly three outcomes and the invariant is that it
    /// never produces a fourth:
    ///
    /// ```text
    /// field absent      ⟹  Ok(None)                    "not supplied"
    /// field = null      ⟹  Ok(Some(None))             "supplied, clear it"
    /// field well-typed  ⟹  Ok(Some(Some(v)))           "supplied, with v"
    /// field wrong-typed ⟹  Err(..)                     "client error"
    /// ```
    ///
    /// The fourth outcome that used to exist is `Ok(None)` for a *present but
    /// wrong-typed* value, because the handler read the body with `Value::as_*`
    /// and `None` from those means "not set". For `rate_limit_rpm` and
    /// `monthly_budget_usd` that is not a missing limit but an *unlimited* one,
    /// and the caller received a `200` and a working key. A value that is
    /// present must be honoured or rejected, never guessed at.
    #[test]
    fn a_present_quota_field_is_honoured_or_rejected_but_never_dropped(
        payload in arb_quota_payload(),
    ) {
        use crate::patch_field;

        let object = payload.as_object().expect("payload is an object");

        for (field, sent) in object {
            if field == "owner" {
                // Parsed as `String`, so a numeric owner is a client error.
                let parsed = patch_field::<String>(&payload, field);
                prop_assert!(
                    parsed.is_err() || parsed.as_ref().unwrap().is_some(),
                    "owner {sent} was dropped rather than rejected or honoured"
                );
                continue;
            }
            match field.as_str() {
                "rate_limit_rpm" => {
                    let parsed = patch_field::<u32>(&payload, field);
                    if sent.is_null() {
                        prop_assert!(
                            matches!(parsed, Ok(Some(None))),
                            "an explicit null must clear the limit, got {parsed:?}"
                        );
                    } else if sent.as_u64().is_some_and(|v| v <= u32::MAX as u64) {
                        prop_assert!(
                            matches!(parsed, Ok(Some(Some(_)))),
                            "a valid rpm {sent} was dropped"
                        );
                    } else {
                        prop_assert!(
                            parsed.is_err(),
                            "{sent} is not a usable rpm but parsed as {parsed:?} \
                             -- a dropped limit reads as unlimited"
                        );
                    }
                }
                "expires_at" => {
                    let parsed = patch_field::<u64>(&payload, field);
                    prop_assert!(
                        parsed.is_err() || matches!(parsed, Ok(Some(_))),
                        "expires_at {sent} was dropped"
                    );
                }
                "allowed_tiers" => {
                    let parsed = patch_field::<Vec<String>>(&payload, field);
                    if sent.is_null() {
                        prop_assert!(matches!(parsed, Ok(Some(None))));
                    } else if sent
                        .as_array()
                        .is_some_and(|items| items.iter().all(Value::is_string))
                    {
                        // A list of tier names is honoured as given.
                        prop_assert!(
                            matches!(parsed, Ok(Some(Some(_)))),
                            "a tier list {sent} was dropped"
                        );
                    } else {
                        // A non-array, or an array holding non-strings, is a
                        // client error. `Err` is correct; `Ok(None)` would be
                        // the bug, because a dropped allowlist reads as *every
                        // tier allowed*.
                        prop_assert!(
                            parsed.is_err(),
                            "{sent} is not a tier list but parsed as {parsed:?} -- \
                             a dropped allowlist reads as every tier allowed"
                        );
                    }
                }
                "monthly_budget_usd" | "client" => {
                    // f64 accepts a JSON number or a numeric string; anything
                    // else must be an error, never a silent None.
                    let parsed = patch_field::<f64>(&payload, field);
                    prop_assert!(
                        parsed.is_err() || matches!(parsed, Ok(Some(_))),
                        "{field} {sent} was dropped rather than rejected or honoured"
                    );
                }
                _ => {}
            }
        }
    }
}

/// `year * 12 + month0` in UTC, via Howard Hinnant's `civil_from_days`.
///
/// This is a *reference* implementation, written independently of the one under
/// test, so the two agreeing is evidence rather than a tautology. Returns the
/// window index for a unix timestamp.
fn calendar_month_index(secs: u64) -> u32 {
    let days = (secs / 86_400) as i64;
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365;
    let year = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let month = if mp < 10 { mp + 3 } else { mp - 9 };
    let year = if month <= 2 { year + 1 } else { year };
    (year * 12 + (month - 1)) as u32
}

/// Whether `secs` is exactly midnight UTC on the first of a month, computed
/// without reference to the implementation under test.
///
/// Walks whole months from a known epoch day and tests membership in each
/// month's span. Deliberately naive: the point is that it shares no code with
/// the civil-date arithmetic it is checking, so agreement is evidence.
fn reference_month_start(secs: u64) -> bool {
    let day = (secs / 86_400) as i64;
    const EPOCH_DAY: i64 = 20_454; // 2026-01-01
    if day < EPOCH_DAY {
        return false;
    }
    let mut start = EPOCH_DAY;
    let mut year = 2026i64;
    loop {
        let leap = year % 4 == 0 && (year % 100 != 0 || year % 400 == 0);
        for month in 0..12i64 {
            let len = if month == 1 && leap {
                29
            } else {
                MONTH_LENGTHS[month as usize]
            };
            // Landing exactly on a month's first day *is* a month start --
            // any month, not only January. An earlier version tested
            // `month == 0` here, so it answered "is this 1 January?" and
            // disagreed with the implementation on every other month.
            if day == start {
                return true;
            }
            if day < start {
                return false;
            }
            start += len;
        }
        year += 1;
    }
}

const MONTH_LENGTHS: [i64; 12] = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
