[package]
name = "miser-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
toml.workspace = true
bytes.workspace = true
clap.workspace = true
futures-util.workspace = true
http.workspace = true
miser-classifier = { path = "../miser-classifier" }
miser-policy = { path = "../miser-policy" }
miser-provider = { path = "../miser-provider" }
miser-types = { path = "../miser-types" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
